### ISSUE TITLE
Multiple Meta file

### ISSUE THREAD

**Issue by martino-jelli** [gwen-interpreter/gwen#21]
Hi gwen Team!

Would be nice to have the option to have more than one meta file per folder.

The reason behind this request is that, like in my case, I need to have an extra metafile ,common.meta file where to specify common methods, like login and logout.

**Comment by bjuric** [comment]
Hi, have you tried one of the following options?

1. Put the common.meta in your top level features folder (assuming all your other meta is in subfolders)

2. Put the common.meta outside of your features folder and pass it in using the `-m <dir>/common.meta` command line option. This option also accepts a comma separated list of meta files if you need to load more.

Otherwise perhaps provide more details. We currently only support one meta per folder for auto discovery since we cannot guarantee load order of many.

**Comment by bradywood** [comment]
Hi Martino, 
Just checking if the folder option helped with your common meta.  If so can we close this issue?

**Comment by bjuric** [comment]
I will add this capability. If loading order causes a problem, then it will be raised or detected one way or another.  If you ensure that your meta files have no 'load time' dependencies between each other, then you will never have this problem. It will be worthwhile having this feature.Thanks

**Comment by bjuric** [comment]
Delivered in release [1.3.0](https://github.com/gwen-interpreter/gwen/releases/tag/v1.3.0)
