### ISSUE TITLE
Unable to click on drop down with bootstrap chosen applied

### ISSUE THREAD

**Issue by bliddicoat** [gwen-interpreter/gwen#30]
Unable to click on a drop down that has the bootstrap chosen css applied to it (http://alxlit.name/bootstrap-chosen/)

This functions correctly with gwen version 1.7.0, though it does not work with the latest version 2.5.0.

**Comment by bjuric** [comment]
Thanks for raising this issue. I've published the following snapshot containing a fix (it uses web driver click instead of JS). Please retest using this snapshot and let me know it goes.
- [gwen-web-2.5.0-1-gbe7d1a6-SNAPSHOT.zip](https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.5.0-1-gbe7d1a6-SNAPSHOT/gwen-web-2.5.0-1-gbe7d1a6-SNAPSHOT.zip)

**Comment by bliddicoat** [comment]
Yes that has fixed the bug. Many thanks.

**Comment by bjuric** [comment]
This fix has been released in gwen-web [v2.5.1](https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.5.1). @bliddicoat, please close when ready. Thanks :)
